version: "3"
services:
  database:
    image: postgres:latest
    container_name: database
    ports:
      - "5432:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/database
      - ./database/create_database.sh:/docker-entrypoint-initdb.d/create_database.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8081:80"
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@beonstudio.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
